version: '3'

services:
  # Configuración del NameNode de Hadoop
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"  # Interfaz web de Hadoop
      - "8020:8020"  # Puerto NameNode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop_network
    depends_on:
      - zookeeper
      - kafka

  # Configuración del DataNode de Hadoop
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    hostname: localhost
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"  # Puerto DataNode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop_network
    depends_on:
      - namenode

  # Configuración de Zookeeper (para Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"  # Puerto Zookeeper
    networks:
      - hadoop_network

  # Configuración de Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-new
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_MESSAGE_MAX_BYTES=10485760
      - KAFKA_MAX_REQUEST_SIZE=10485760
      - KAFKA_COMPRESSION_TYPE=gzip
    ports:
      - "9092:9092"  # Puerto Kafka
    networks:
      - hadoop_network
    depends_on:
      - zookeeper

  # MongoDB (si lo necesitas para almacenamiento adicional)
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"  # Puerto MongoDB
  #   networks:
  #     - hadoop_network

# Volúmenes de datos de Hadoop
volumes:
  hadoop_namenode:
  hadoop_datanode:

# Redes
networks:
  hadoop_network:
    driver: bridge